# Generated by Django 6.0.4 on 2026-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(default='1080p', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(blank=True, default='120', max_length=20),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.genre'),
        ),
    ]
